image: Ubuntu1804 # образ для сборки
stack: node 10 # окружение
branches: 
  only:
    - master # ветка git
cache: node_modules # кеширование
install:
  - yarn # команда установки зависимостей
build: off
build_script:
  - yarn build # команда сборки
# test_script:
#   - yarn test # скрипт тестирования
deploy_script: # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=build --branch=gh-pages --force --verbose